const text = {
    en: {
        h1: "Stay in Touch With Sadhguru and Isha",
        quote: "“A world full of love, light and laughter, its time has come. Let us make it happen.” —Sadhguru",
        btn1: "Learn More",
        btn2: "Join Now",
        p1: "Would you like to access more of Sadhguru’s wisdom and content?",
        p2: "Are you interested in other free online Yoga and meditation sessions to enhance your emotional balance, physical wellbeing and mental health?",
        p3: "Here are 3 ways to stay in touch, wherever you may be:",
        p4: "Our free Isha Yoga Webinars include simple Yogic practices and guided meditations along with Sadhguru’s wisdom addressing various aspects of life such as health, peace and success.",
        p5: "Experience Inner Engineering with Sadhguru in your own space, at your own pace. Inner Engineering Online is comprised of seven 90-minute sessions that impart powerful tools from the ancient science of Yoga, with the potential of transforming the very way you live, conduct and experience your life.",
        h2: "Receive monthly updates on Sadhguru and Isha’s activities in your region. Join below!",
        h3: "For More Free Yoga & Meditations, Check out the Sadhguru App",
        h4: "Inner Engineering Online",
        form1: "Full Name",
        form2: "Email Address",
        form3: "Country"
    },
    ru: {
        h1: "Оставайтесь на связи с Садхгуру и Ишей",
        quote: "“Мир, полный любви, света и смеха, - его время пришло. Давайте сделаем так, чтобы это произошло.” — Садхгуру",
        btn1: "Узнать больше",
        btn2: "Join Now",
        p1: "Вы хотите получить доступ к мудрости и материалам Садхгуру?",
        p2: "Вас интересуют другие бесплатные онлайн-сессии по йоге и медитации для улучшения эмоционального равновесия, физического и психического здоровья?",
        p3: "Вот 3 способа оставаться на связи, где бы вы ни находились:",
        p4: "Our free Isha Yoga Webinars include simple Yogic practices and guided meditations along with Sadhguru’s wisdom addressing various aspects of life such as health, peace and success.",
        p5: "Пройдите курс \"Внутренняя инженерия\" с Садхгуру в вашем собственном пространстве, в вашем собственном темпе. Inner Engineering Online состоит из семи 90-минутных сессий, которые передают мощные инструменты из древней науки Йоги, способные изменить сам образ вашей жизни, поведение и опыт.",
        h2: "Receive monthly updates on Sadhguru and Isha’s activities in your region. Join below!",
        h3: "For More Free Yoga & Meditations, Check out the Sadhguru App",
        h4: "Внутренняя инженерия онлайн",
        form1: "Full Name",
        form2: "Email Address",
        form3: "Country"
    },
    it: {
        h1: "Rimani in contatto con Sadhguru e Isha",
        quote: "“Un mondo pieno di amore, luce e risate, il suo tempo è arrivato. Facciamo in modo che accada.” —Sadhguru",
        btn1: "Per saperne di più",
        btn2: "Join Now",
        p1: "Vuoi accedere a più saggezza e contenuti di Sadhguru?",
        p2: "Sei interessato ad altre sessioni gratuite di Yoga e meditazione online per migliorare il tuo equilibrio emotivo, il benessere fisico e la salute mentale?",
        p3: "Ecco 3 modi per rimanere in contatto, ovunque tu sia:",
        p4: "Our free Isha Yoga Webinars include simple Yogic practices and guided meditations along with Sadhguru’s wisdom addressing various aspects of life such as health, peace and success.",
        p5: "Sperimenta l'Ingegneria Interiore con Sadhguru nel tuo spazio, al tuo ritmo. L'Inner Engineering Online è composto da sette sessioni di 90 minuti che impartiscono potenti strumenti dall'antica scienza dello Yoga, con il potenziale di trasformare il tuo modo di vivere, condurre e sperimentare la tua vita.",
        h2: "Receive monthly updates on Sadhguru and Isha’s activities in your region. Join below!",
        h3: "For More Free Yoga & Meditations, Check out the Sadhguru App",
        h4: "Ingegneria Interiore Online",
        form1: "Full Name",
        form2: "Email Address",
        form3: "Country"
    },
    es: {
        h1: "Mantente en contacto con Sadhguru e Isha",
        quote: "“Un mundo lleno de amor, luz y risas, ha llegado su hora. Hagámoslo realidad.” —Sadhguru",
        btn1: "Más información",
        btn2: "Join Now",
        p1: "¿Te gustaría acceder a más sabiduría y contenido de Sadhguru?",
        p2: "¿Estás interesado en otras sesiones gratuitas de yoga y meditación online para mejorar tu equilibrio emocional, tu bienestar físico y tu salud mental?",
        p3: "Aquí tienes 3 formas de estar en contacto, estés donde estés:",
        p4: "Our free Isha Yoga Webinars include simple Yogic practices and guided meditations along with Sadhguru’s wisdom addressing various aspects of life such as health, peace and success.",
        p5: "Experimenta la Ingeniería Interior con Sadhguru en tu propio espacio, a tu propio ritmo. Ingeniería Interior en línea se compone de siete sesiones de 90 minutos que imparten poderosas herramientas de la antigua ciencia del Yoga, con el potencial de transformar la forma en que vives, conduces y experimentas tu vida.",
        h2: "Receive monthly updates on Sadhguru and Isha’s activities in your region. Join below!",
        h3: "For More Free Yoga & Meditations, Check out the Sadhguru App",
        h4: "Ingeniería Interior en Línea",
        form1: "Full Name",
        form2: "Email Address",
        form3: "Country"
    },
    de: {
        h1: "Bleib in Kontakt mit Sadhguru und Isha",
        quote: "“Eine Welt voller Liebe, Licht und Lachen, ihre Zeit ist gekommen. Lasst es uns wahr machen.” —Sadhguru",
        btn1: "Mehr erfahren",
        btn2: "Sich einschreiben",
        p1: "Möchtest du mehr von Sadhgurus Weisheit und Inhalten erfahren?",
        p2: "Bist du an weiteren kostenlosen Online-Yoga- und Meditations-Sitzungen interessiert, um dein emotionales Gleichgewicht, dein körperliches Wohlbefinden und deine geistige Gesundheit zu verbessern?",
        p3: "Hier sind Möglichkeiten, um in Kontakt zu bleiben, wo immer du auch sein magst:",
        p4: "Our free Isha Yoga Webinars include simple Yogic practices and guided meditations along with Sadhguru’s wisdom addressing various aspects of life such as health, peace and success.",
        p5: "Erfahre Inner Engineering mit Sadhguru in deiner eigenen Geschwindigkeit bei dir zu Hause. Inner Engineering besteht aus sieben wirkungsvollen Sitzungen, in denen kraftvolle Werkzeuge aus der uralten Wissenschaft des Yoga vermittelt werden, die die Art und Weise, wie du lebst, wie du dein Leben führst und erfährst, transformieren können.",
        h2: "Erhalte die monatlichen Updates über Sadhgurus und Ishas Aktivitäten in deiner Region. Melde dich unten an!",
        h3: "Für mehr kostenlose Meditations & Yogainhalte, schau auf dem Sadhguru Deutsch Kanal",
        h4: "Inner Engineering Online",
        form1: "Vollständiger Name",
        form2: "E-Mail Adresse",
        form3: "Land"
    },
    fr: {
        h1: "Restez en contact avec Sadhguru et Isha",
        quote: "“Un monde plein d'amour, de lumière et de rires, son heure est venue. Faisons en sorte qu'il se réalise.” —Sadhguru",
        btn1: "En savoir plus",
        btn2: "S'inscrire maintenant",
        p1: "Souhaitez-vous accéder à davantage de sagesse et de contenu de Sadhguru?",
        p2: "Êtes-vous intéressé par d'autres séances gratuites de yoga et de méditation en ligne pour améliorer votre équilibre émotionnel, votre bien-être physique et votre santé mentale?",
        p3: "Voici 3 façons de rester en contact, où que vous soyez ::",
        p4: "Our free Isha Yoga Webinars include simple Yogic practices and guided meditations along with Sadhguru’s wisdom addressing various aspects of life such as health, peace and success.",
        p5: "Faites l'expérience du génie intérieur avec Sadhguru dans votre propre espace, à votre propre rythme. Inner Engineering Online est composé de sept sessions de 90 minutes qui transmettent des outils puissants issus de l'ancienne science du yoga, avec le potentiel de transformer la façon dont vous vivez, conduisez et expérimentez votre vie.",
        h2: "Recevez des mises à jour mensuelles sur les activités de Sadhguru et d'Isha dans votre région. Inscrivez-vous ci-dessous!",
        h3: "Pour plus de pratiques gratuites de yoga et de méditation, consultez la chaîne Sadhguru Français.",
        h4: "Ingénierie intérieure en ligne",
        form1: "Nom complet",
        form2: "Adresse e-mail",
        form3: "Pays"
    }
}

export default text